package CSGUI;

import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;
import entity.CPU;
import util.SQLHelper;

import javax.swing.*;
import java.awt.*;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.util.*;
import java.util.List;

import util.datachooser;

/**
 * Created by Administrator on 2017/5/5 0005.
 */
public class test {
    private JTextArea infomation;
    public JPanel date;
    private JComboBox mac;
    private JButton serchButton;
    public JComboBox type;
    public static String macinfo = null;
    public static String typeinfo = null;


    public test() {
        mac.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent e) {
                try {
                    setlist(e);
                } catch (SQLException e1) {
                    e1.printStackTrace();
                }
            }
        });
        serchButton.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent e) {
                try {
                    serchinfo(e);
                } catch (SQLException e1) {
                    e1.printStackTrace();
                }
            }
        });
    }

    public void serchinfo(MouseEvent e) throws SQLException {
        macinfo = mac.getSelectedItem().toString();
        typeinfo = type.getSelectedItem().toString();//取cpu/net/..信息
        String[] sourceStrArray = macinfo.split("--");
        String macstring = sourceStrArray[1];//mac地址
        String sql = "SELECT * from " + typeinfo + " where Hwaddr='" + macstring + "' and date(time)='" + datachooser.string + "'";
        SQLHelper sqlhelp = new SQLHelper();
        ResultSet rs = sqlhelp.executeQuery(sql);
//        while (rs.next()) {
//            infomation.append(rs.getString("UserNmae"));
//        }
        ResultSetMetaData rsmd = rs.getMetaData();
        int columnsNumber = rsmd.getColumnCount();
        infomation.setText("");
        while (rs.next()) {
            for (int i = 2; i <= columnsNumber; i++) {
                infomation.append("\n");
                String columnValue = rs.getString(i);
                infomation.append(rsmd.getColumnName(i) + " " + columnValue);
            }
            infomation.append("\n");
        }
    }

    public void setlist(MouseEvent e) throws SQLException {
        String sql = "SELECT Hwaddr ,name from mac limit 5";
        SQLHelper sqlHelper = new SQLHelper();
        ResultSet rs = sqlHelper.executeQuery(sql);
        mac.removeAllItems();//清楚所有下拉表单，防止重复..
        while (rs.next()) {
            mac.addItem(rs.getString("name") + "--" + rs.getString("Hwaddr"));

        }
    }

    public static void main(String[] args) {
        JFrame frame = new JFrame("test");
        frame.setContentPane(new test().date);
        frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        frame.pack();
        frame.setVisible(true);
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        date = new JPanel();
        date.setLayout(new GridLayoutManager(4, 3, new Insets(0, 0, 0, 0), -1, -1));
        date.setPreferredSize(new Dimension(600, 550));
        final datachooser datachooser1 = new datachooser();
        date.add(datachooser1, new GridConstraints(0, 2, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 0, false));
        mac = new JComboBox();
        final DefaultComboBoxModel defaultComboBoxModel1 = new DefaultComboBoxModel();
        mac.setModel(defaultComboBoxModel1);
        date.add(mac, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        type = new JComboBox();
        final DefaultComboBoxModel defaultComboBoxModel2 = new DefaultComboBoxModel();
        defaultComboBoxModel2.addElement("CPU");
        defaultComboBoxModel2.addElement("Disk");
        defaultComboBoxModel2.addElement("Memory");
        defaultComboBoxModel2.addElement("Net");
        defaultComboBoxModel2.addElement("Os");
        defaultComboBoxModel2.addElement("Who");
        type.setModel(defaultComboBoxModel2);
        date.add(type, new GridConstraints(0, 1, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        serchButton = new JButton();
        serchButton.setText("serch");
        date.add(serchButton, new GridConstraints(1, 1, 3, 2, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final JScrollPane scrollPane1 = new JScrollPane();
        date.add(scrollPane1, new GridConstraints(1, 0, 3, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_WANT_GROW, null, null, null, 0, false));
        infomation = new JTextArea();
        infomation.setLineWrap(true);
        scrollPane1.setViewportView(infomation);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return date;
    }
}
